apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: P002
    access: proxy
    url: ${PROMETHEUS_URL}
    jsonData:
      tlsSkipVerify: true
      httpMethod: POST
      manageAlerts: false
      prometheusType: Prometheus
      prometheusVersion: 2.44.0
      cacheLevel: "High"
      disableRecordingRules: false
    editable: false
    isDefault: false
    orgId: 1
    version: 1
