"""ActVersion repository interface."""

from __future__ import annotations

from typing import Protocol, runtime_checkable

from domain.entities.act_version import ActVersion


@runtime_checkable
class ActVersionRepository(Protocol):
    async def create(self, version: ActVersion) -> ActVersion: ...
    async def get_by_id(self, version_id: int) -> ActVersion | None: ...
    async def get_by_document_id(
        self, document_id: int, *, for_update: bool = False
    ) -> ActVersion | None: ...
    async def unset_current(self, act_id: int) -> None: ...
    async def list_by_act(self, act_id: int) -> list[ActVersion]: ...
    async def list_pending_review(self) -> list[ActVersion]: ...
    async def list_page(self, limit: int, offset: int) -> tuple[list[ActVersion], int]: ...
    async def update(self, version: ActVersion) -> None: ...
