"""Assignment repository -- protocol for user/group assignment persistence."""

from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class AssignmentRepository(Protocol):
    async def get_managed_user_ids(self, manager_id: int) -> list[int]: ...
    async def get_managed_client_ids(self, manager_id: int) -> list[int]: ...
    async def get_managed_internal_ids(self, manager_id: int) -> list[int]: ...
    async def get_managed_group_ids(self, manager_id: int) -> list[int]: ...
    async def assign_user(self, manager_id: int, target_user_id: int, assigned_by: int) -> None: ...
    async def unassign_user(self, manager_id: int, target_user_id: int) -> None: ...
    async def assign_group(self, manager_id: int, group_id: int, assigned_by: int) -> None: ...
    async def unassign_group(self, manager_id: int, group_id: int) -> None: ...
    async def clear_all_for_manager(self, manager_id: int) -> None: ...
    async def list_managers_for_group(self, group_id: int) -> list[int]: ...
