"""Background job repository interface -- tracking for async background tasks."""

from __future__ import annotations

from typing import Protocol

from domain.entities.background_job import BackgroundJob


class BackgroundJobRepository(Protocol):
    async def create(self, job: BackgroundJob) -> BackgroundJob: ...
    async def mark_running(self, job_id: int) -> None: ...
    async def mark_done(self, job_id: int) -> None: ...
    async def mark_failed(self, job_id: int, error: str) -> None: ...
    async def count_active(self) -> int: ...
    async def delete_old(self, days: int) -> int: ...
    async def list_recent(self, limit: int = 50, offset: int = 0) -> list[BackgroundJob]: ...
    async def get_by_id(self, job_id: int) -> BackgroundJob | None: ...
    async def count_by_status(self) -> dict[str, int]: ...
    async def recover_orphaned(self, timeout_minutes: int = 15) -> list[int]: ...
