"""Client Assignment Repository interface."""

from __future__ import annotations

from typing import Protocol


class ClientAssignmentRepository(Protocol):
    def assign(self, internal_user_id: int, client_user_id: int, assigned_by: int) -> None: ...
    def unassign(self, internal_user_id: int, client_user_id: int) -> None: ...
    def get_assigned_client_ids(self, internal_user_id: int) -> list[int]: ...
    def list_for_client(self, client_user_id: int) -> list[dict]: ...
