"""Group repository interface -- CRUD for user groups (ACL boundaries)."""

from __future__ import annotations

from typing import Protocol, runtime_checkable

from domain.value_objects.query_results import GroupInfo, GroupMemberInfo


@runtime_checkable
class GroupRepository(Protocol):
    async def create(self, name: str) -> int: ...
    async def list_all(self) -> list[GroupInfo]: ...
    async def list_by_ids(self, ids: list[int]) -> list[GroupInfo]: ...
    async def get_user_group_ids(self, user_id: int) -> list[int]: ...
    async def add_user(self, user_id: int, group_id: int) -> None: ...
    async def remove_user(self, user_id: int, group_id: int) -> None: ...
    async def list_members(self, group_id: int) -> list[GroupMemberInfo]: ...
