"""Group Repository interface."""

from __future__ import annotations

from typing import Protocol


class GroupRepository(Protocol):
    async def create(self, name: str) -> int: ...
    async def list_all(self) -> list[dict]: ...
    async def list_by_ids(self, ids: list[int]) -> list[dict]: ...
    async def get_user_group_ids(self, user_id: int) -> list[int]: ...
    async def add_user(self, user_id: int, group_id: int) -> None: ...
    async def remove_user(self, user_id: int, group_id: int) -> None: ...
    async def list_members(self, group_id: int) -> list[dict]: ...
