"""User Repository interface."""

from __future__ import annotations

from typing import Protocol

from domain.entities.user import User


class UserRepository(Protocol):
    def get_by_id(self, user_id: int) -> User | None: ...
    def get_by_email(self, email: str) -> User | None: ...
    def save(self, user: User) -> User: ...
    def exists_admin(self) -> bool: ...
    def list_all(self) -> list[User]: ...
    def set_active(self, user_id: int, is_active: bool) -> bool: ...
