"""User repository interface -- CRUD and lookup for User entities."""

from __future__ import annotations

from typing import Protocol, runtime_checkable

from domain.entities.user import User


@runtime_checkable
class UserRepository(Protocol):
    async def get_by_id(self, user_id: int) -> User | None: ...
    async def get_by_email(self, email: str) -> User | None: ...
    async def save(self, user: User) -> User: ...
    async def exists_admin(self) -> bool: ...
    async def list_all(self) -> list[User]: ...
    async def set_active(self, user_id: int, is_active: bool) -> bool: ...
