"""Vector store repository interface -- abstracts embedding generation and Qdrant operations."""

from __future__ import annotations

from typing import Protocol, runtime_checkable

from domain.entities.chunk import Chunk


@runtime_checkable
class VectorStoreRepository(Protocol):
    async def ensure_collection(self, vector_size: int, reset: bool = False) -> None: ...
    async def upload_documents(self, chunks: list[Chunk]) -> None: ...
    async def delete_by_document_id(self, document_id: int) -> None: ...
    async def generate_embeddings(self, text: str) -> list[float]: ...
    async def similarity_search_with_score(self, query: str, k: int) -> list[tuple[Chunk, float]]: ...
    async def upsert_point(self, point_id: int, vector: list[float], payload: dict) -> None: ...
    async def get_point_payload(self, point_id: int) -> dict | None: ...
    async def delete_by_ids(self, ids: list[int]) -> None: ...
