"""Vector store repository interface -- abstracts embedding generation and Qdrant operations."""

from __future__ import annotations

from collections.abc import Awaitable, Callable
from typing import Any, Protocol, runtime_checkable

from domain.entities.chunk import Chunk


@runtime_checkable
class VectorStoreRepository(Protocol):
    async def ensure_collection(self, vector_size: int, reset: bool = False) -> None: ...
    async def upload_documents(
        self,
        chunks: list[Chunk],
        *,
        should_cancel: Callable[[], Awaitable[bool]] | None = None,
    ) -> None: ...
    async def delete_by_document_id(self, document_id: int) -> None: ...
    async def generate_embeddings(self, text: str) -> list[float]: ...
    async def upsert_point(self, point_id: int, vector: list[float], payload: dict) -> None: ...
    async def get_point_payload(self, point_id: int, access_filter: Any) -> dict | None: ...
    async def delete_by_ids(self, ids: list[int]) -> None: ...
    async def set_document_id_by_source(self, source: str, document_id: int) -> None: ...
    async def update_filename_by_document_id(self, document_id: int, new_filename: str) -> None: ...
    async def update_metadata_by_act_version(self, act_version_id: int, metadata_updates: dict) -> None: ...
