apiVersion: v1
kind: Service
metadata:
  name: {{ include "rag-app.fullname" . }}-server
  labels:
    {{- include "rag-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "rag-app.server.selectorLabels" . | nindent 4 }}
