"""IngestionPort -- application-layer abstraction for the document ingestion pipeline.

Defines the protocol that ``IngestAppService`` depends on.  The concrete
implementation (local files, S3, hybrid) lives in ``infrastructure.services``.
"""

from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class IngestionPort(Protocol):
    def resolve_docs_dir(self, docs_dir: str) -> str: ...
    async def run_full_ingestion(
        self, docs_dir: str, reset: bool = False, prefix: str | None = None, domain: str = "auto"
    ) -> None: ...
    def resolve_ingest_target(self, file_path: str) -> str: ...
    async def run_single_file(self, file_path: str, domain: str = "auto") -> None: ...
    def get_registry(self) -> dict[str, Any]: ...
    def force_reindex(self, filename: str) -> None: ...
    async def upload_files(self, files: Any, prefix: str = "docs/") -> list[str]: ...
