"""IngestionPort — application-layer abstraction for document ingestion."""

from __future__ import annotations

from typing import Any, Protocol


class IngestionPort(Protocol):
    def resolve_docs_dir(self, docs_dir: str) -> str: ...
    async def run_full_ingestion(
        self, docs_dir: str, reset: bool = False, prefix: str | None = None
    ) -> None: ...
    def resolve_ingest_target(self, file_path: str) -> str: ...
    async def run_single_file(self, file_path: str) -> None: ...
    def get_registry(self) -> dict[str, Any]: ...
    def force_reindex(self, filename: str) -> None: ...
    def upload_files(self, files: Any, prefix: str = "docs/") -> list[str]: ...
