"""Async Session Protocol — abstract database session interface."""

from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class SessionProtocol(Protocol):
    """Abstract session interface matching SQLAlchemy AsyncSession API."""

    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...
    async def close(self) -> None: ...
    async def flush(self) -> None: ...
    async def execute(self, statement, params=None): ...
