"""add_allowed_values for parametrs

Revision ID: 8e19a1cfb758
Revises: c3d4e5f6a7b8
Create Date: 2026-08-06 07:11:22.451737

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8e19a1cfb758"
down_revision: str | Sequence[str] | None = "c3d4e5f6a7b8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("idx_api_keys_user_id"), table_name="api_keys")
    op.alter_column(
        "background_jobs",
        "started_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=True,
    )
    op.alter_column(
        "background_jobs",
        "finished_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=True,
    )
    op.drop_index(op.f("idx_background_jobs_creation_date"), table_name="background_jobs")
    op.drop_index(op.f("idx_background_jobs_job_type"), table_name="background_jobs")
    op.drop_index(op.f("idx_background_jobs_status"), table_name="background_jobs")
    op.add_column("config_parameters", sa.Column("allowed_values", sa.JSON(), nullable=True))
    op.drop_index(op.f("idx_config_parameters_category"), table_name="config_parameters")
    op.drop_index(op.f("idx_conversations_user"), table_name="conversations")
    op.drop_index(op.f("idx_documents_group"), table_name="documents")
    op.drop_index(op.f("idx_documents_owner"), table_name="documents")
    op.drop_index(op.f("idx_documents_status"), table_name="documents")
    op.drop_index(op.f("idx_documents_visibility"), table_name="documents")
    op.drop_index(
        op.f("ux_documents_active_slot"),
        table_name="documents",
        postgresql_where="((status)::text = ANY ((ARRAY['pending'::character varying, 'processing'::character varying, 'done'::character varying])::text[]))",
    )
    op.drop_index(op.f("idx_messages_conv"), table_name="messages")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("idx_messages_conv"), "messages", ["conversation_id"], unique=False)
    op.create_index(
        op.f("ux_documents_active_slot"),
        "documents",
        ["owner_id", "filename"],
        unique=True,
        postgresql_where="((status)::text = ANY ((ARRAY['pending'::character varying, 'processing'::character varying, 'done'::character varying])::text[]))",
    )
    op.create_index(op.f("idx_documents_visibility"), "documents", ["visibility"], unique=False)
    op.create_index(op.f("idx_documents_status"), "documents", ["status"], unique=False)
    op.create_index(op.f("idx_documents_owner"), "documents", ["owner_id"], unique=False)
    op.create_index(op.f("idx_documents_group"), "documents", ["group_id"], unique=False)
    op.create_index(op.f("idx_conversations_user"), "conversations", ["user_id"], unique=False)
    op.create_index(op.f("idx_config_parameters_category"), "config_parameters", ["category"], unique=False)
    op.drop_column("config_parameters", "allowed_values")
    op.create_index(op.f("idx_background_jobs_status"), "background_jobs", ["status"], unique=False)
    op.create_index(op.f("idx_background_jobs_job_type"), "background_jobs", ["job_type"], unique=False)
    op.create_index(
        op.f("idx_background_jobs_creation_date"), "background_jobs", ["creation_date"], unique=False
    )
    op.alter_column(
        "background_jobs",
        "finished_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=True,
    )
    op.alter_column(
        "background_jobs",
        "started_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=True,
    )
    op.create_index(op.f("idx_api_keys_user_id"), "api_keys", ["user_id"], unique=False)
    # ### end Alembic commands ###
